on:
    pull_request:
      types:
        - opened
        - synchronize
        - reopened
  
jobs:
    test:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        

  
        - name: Get changed Python files
          run: | 
            BASE_BRANCH=$(git rev-parse origin/main)
            CHANGED_FILES=$(git diff --name-only $BASE_BRANCH HEAD | grep '^tests/.*\.py$' || true)
            echo "Changed Python Test Files: $CHANGED_FILES"
         
  
        - name: Install Python dependencies
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"
  
        - name: Install Python dependencies and pytest
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pytest
          
  
        - name: Print directory contents
          run: |
            ls -R
  
        - name: Run affected tests
          run: |
              if [ -n "$CHANGED_FILES" ]; then
                echo $GITHUB_WORKSPACE
                cd $GITHUB_WORKSPACE
                python -m pytest -v -x "$(echo "$CHANGED_FILES")"
              else
                echo "No Python test files changed. Skipping tests."
              fi